// <auto-generated />
using System;
using Lingva.DAL.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lingva.DAL.EF.Migrations
{
    [DbContext(typeof(DictionaryContext))]
    [Migration("20190520154636_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lingva.DAL.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreateDate");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int>("LanguageId");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("Name");

                    b.Property<string>("Picture");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(4849),
                            Date = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(4859),
                            Description = "Good movie",
                            LanguageId = 1,
                            ModifyDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(4857),
                            Name = "Harry Potter",
                            Picture = "1"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(6163),
                            Date = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(6174),
                            Description = "Eq",
                            LanguageId = 1,
                            ModifyDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(6171),
                            Name = "Librium",
                            Picture = "2"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(6188),
                            Date = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(6193),
                            Description = "stuff",
                            LanguageId = 2,
                            ModifyDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(6190),
                            Name = "2Guns",
                            Picture = "3"
                        });
                });

            modelBuilder.Entity("Lingva.DAL.Entities.GroupUser", b =>
                {
                    b.Property<int>("GroupId");

                    b.Property<int>("UserId");

                    b.Property<DateTime?>("CreateDate");

                    b.Property<int>("Id");

                    b.Property<DateTime?>("ModifyDate");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupUser");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            UserId = 1,
                            CreateDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(7740),
                            Id = 1,
                            ModifyDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(7744)
                        },
                        new
                        {
                            GroupId = 1,
                            UserId = 2,
                            CreateDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(8636),
                            Id = 2,
                            ModifyDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(8643)
                        });
                });

            modelBuilder.Entity("Lingva.DAL.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreateDate");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2019, 5, 20, 18, 46, 36, 573, DateTimeKind.Local).AddTicks(3341),
                            ModifyDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(1930),
                            Name = "en"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(3265),
                            ModifyDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(3273),
                            Name = "ru"
                        });
                });

            modelBuilder.Entity("Lingva.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("Email");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(6456),
                            Email = "veloceraptor89@gmail.com",
                            ModifyDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(6460),
                            Name = "Serhii"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(7520),
                            Email = "tucker_serega@mail.ru",
                            ModifyDate = new DateTime(2019, 5, 20, 18, 46, 36, 577, DateTimeKind.Local).AddTicks(7527),
                            Name = "Old"
                        });
                });

            modelBuilder.Entity("SenderService.Email.EF.DAL.Entities.EmailSendingOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Host");

                    b.Property<string>("Password");

                    b.Property<int>("Port");

                    b.Property<bool>("UseSsl");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("EmailSendingOption");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Host = "smtp.gmail.com",
                            Password = "worksoftserve_90",
                            Port = 587,
                            UseSsl = false,
                            UserName = "worksoftserve@gmail.com"
                        });
                });

            modelBuilder.Entity("SenderService.Email.EF.DAL.Entities.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ParametersString");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplate");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ParametersString = "GroupName; GroupDate",
                            Text = "You will have meeting {{GroupName}} at {{GroupDate}}"
                        });
                });

            modelBuilder.Entity("Lingva.DAL.Entities.Group", b =>
                {
                    b.HasOne("Lingva.DAL.Entities.Language", "Language")
                        .WithMany("Groups")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Lingva.DAL.Entities.GroupUser", b =>
                {
                    b.HasOne("Lingva.DAL.Entities.Group", "Group")
                        .WithMany("GroupUsers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Lingva.DAL.Entities.User", "User")
                        .WithMany("GroupUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
